version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app
    command: 'npm run dev'
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    external: true

